task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from tasks import views
from profile_management import views
from chatapp import views
from .views import HomeView

app_name = 'base_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('tasks/', include('tasks.urls')),
    path('profile/', include('profile_management.urls')),
    path('rooms/', include('chatapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='task_manager/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'), 
]

task_manager/tasks/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views

app_name = 'tasks_app'

urlpatterns = [
    # URL for listing all projects
    path('', views.HomeView.as_view(), name='home'),

    # URL for viewing details of a specific project

    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/new/', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_edit'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),

    # URL for viewing details of a specific task
    path('tasks/<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),

    # URL for creating a new task within a project
    path('projects/<int:pk>/tasks/new/', views.TaskCreateView.as_view(), name='task_create'),

    # URL for editing a task
    path('tasks/<int:pk>/edit/', views.TaskUpdateView.as_view(), name='task_edit'),

    # URL for deleting a task
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),


    # path('chat/<str:room_name>/', views.chat, name='chat'),

    # path('message/<int:message_id>/delete/', views.delete_message, name='delete_message'),
    # path('message/<int:message_id>/edit/', views.edit_message, name='edit_message'),

]

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(User, related_name='tasks', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    due_date = models.DateTimeField(default=datetime.datetime.now)
    is_completed = models.BooleanField(default=False)

task_manager/tasks/views.py
from django import forms
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  RedirectView, UpdateView)

from .models import Project, Task
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

class HomeView(RedirectView):
    url = reverse_lazy('tasks_app:project_list')

class ProjectListView(ListView):
    model = Project
    template_name = 'tasks/project_list.html'

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'tasks/project_detail.html'

class ProjectCreateView(CreateView):
    model = Project
    fields = ['name', 'description']
    template_name = 'tasks/project_form.html'
    success_url = '/tasks'

class ProjectUpdateView(UpdateView):
    model = Project
    fields = ['name', 'description']
    template_name = 'tasks/project_form.html'
    def get_success_url(self):
        return reverse('project_detail', kwargs={'pk': self.object.id})

class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'tasks/project_confirm_delete.html'
    success_url = '/tasks'

class TaskDetailView(DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
#====================================================

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'project', 'assigned_to', 'due_date', 'is_completed']
        widgets = {
            'due_date': forms.DateTimeInput(attrs={'type': 'text', 'class': 'form-control datetimepicker'}, format='%Y-%m-%d %H:%M')
        }

class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_form.html'
    def get_success_url(self):
        return reverse('tasks_app:project_detail', kwargs={'pk': self.object.project.id})

class TaskUpdateView(UpdateView):
    model = Task
    fields = ['title', 'description', 'project', 'assigned_to', 'due_date', 'is_completed']
    template_name = 'tasks/task_form.html'
    def get_success_url(self):
        return reverse('tasks_app:project_detail', kwargs={'pk': self.object.project.id})

class TaskDeleteView(DeleteView):
    model = Task
    fields = ['title', 'project']
    template_name = 'tasks/task_confirm_delete.html'
    def get_success_url(self):
        return reverse('tasks_app:project_detail', kwargs={'pk': self.object.project.id})


##################################################################################################################

task_manager/tasks/templates/tasks/chat_page.html
{% extends "task_manager/base.html" %}

{% block content %}
<div class="container" id="chat-page">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8" id="chat-log">
            {% for message in messages %}
            <div 
            class="msg {% if message.author.id == request.user.id %}message-right{% else %}message-left{% endif %}" 
            data-message-id="{{ message.id }}" 
            data-is-own-message="{% if message.author.id == request.user.id %}true{% else %}false{% endif %}">
                <p style="margin-top: 10pt;">
                    <b style="font-size: 11pt; padding-left: 5px;">{{ message.author.username }} </b>
                    <span id="msg-date" style="padding-right: 5px;">{{ message.timestamp|date:"m/d/Y H:iA" }}</span></br>
                    <button id="message-container" type="button" class="btn message-badge {% if message.author == request.user %}btn-success msgRight {% else %}btn-secondary msgLeft{% endif %} position-relative" data-author-id="{{ message.author.id }}" data-user-id="{{ request.user.id }}" data-message-id="{{ message.id }}">
                        {{ message.content }}
                    </button>
                </p>
            </div>
            {% endfor %}
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row mt-1">
        <div class="col-2"></div>
        <div class="col-8 p-10 px-0 mx-0">
            <div class="d-flex flex-row mb-3">
                <button class="btn px-0 mx-0 flex-shrink-1 align-self-start" id="add-more-btn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
                      </svg>
                </button>
                <textarea class="align-self-start mx-0 w-100" id="chat-message-input" rows="1" placeholder="Type your message..."></textarea>
                <button class="btn btn-primary px-0 mx-0 flex-shrink-1 align-self-start" id="chat-message-submit" type="button" value="Send">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
                        <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                    </svg>
                </button>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>
<script type="text/javascript">
    var roomName = {{ room_name_json|safe }};
    const currentUsername = "{{ current_user|escapejs }}";
    const currentUserId = "{{ current_user_id|escapejs }}";
</script>
{% endblock %}

task_manager/tasks/templates/tasks/project_confirm_delete.html
{% extends "task_manager/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Are you sure you want to delete {{ object.name }}?</h1>
    </div>
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirm Delete</button>
            <a href="{% url 'tasks_app:project_list' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}
{% load static %} 
{% block scripts %}
<script src="{% static 'js/websocket_handling.js' %}"></script>
{% endblock %}

task_manager/tasks/templates/tasks/project_detail.html
{% extends "task_manager/base.html" %}

{% block content %}
<div class="container">
    <h1 class="pt-3 pb-3">{{ project.name }}</h1>
    <p>Description: {{ project.description }}</p>
    <a href="{% url 'tasks_app:project_edit' project.id %}">Edit Project</a> |
    <a href="{% url 'tasks_app:project_delete' project.id %}">Delete Project</a>
</div>

<div class="container">
    <div class="row pt-3">
       <h2>Tasks</h2> 
    </div>
    <div class="list-group" id="tasks-container">
        {% for task in project.tasks.all %}
                <label class="list-group-item d-flex gap-3 task" id="task-{{ task.id }}">
                  <input class="form-check-input flex-shrink-0" type="checkbox" value="" checked="" style="font-size: 1.375em;">
                  <span class="pt-1 form-checked-content">
                    <strong>{{ task.title }}</strong>
                    <small class="d-block text-body-secondary">
                      <svg class="bi me-1" width="1em" height="1em"><use xlink:href="#calendar-event"></use></svg>
                      {{ task.due_date }}
                    </small>
                  </span>
                  <a href="{% url 'tasks_app:task_delete' task.id %}" class="btn btn-danger pb-0">Delete</a>
                </label>
        {% endfor %}
    </div>
    <a href="{% url 'tasks_app:task_create' project.id %}">Add New Task</a>
</div>

{% endblock %}
{% load static %} 
{% block scripts %}
<script src="{% static 'js/websocket_handling.js' %}"></script>
{% endblock %}

task_manager/tasks/templates/tasks/project_form.html
{% extends "task_manager/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container p-2">
    <div class="row">
        <h2>{% if object %}Edit Project{% else %}Create Project{% endif %}</h2>
    </div>
    <form method="post" class="form">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:"form-control" }}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pt-2">
           <button type="submit" class="btn btn-primary">Save</button> 
        </div>
        
    </form> 
</div>

{% endblock %}

task_manager/tasks/templates/tasks/project_list.html
<!-- tasks/templates/tasks/project_list.html -->
{% extends "task_manager/base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
            <h1 class="ps-3 pt-3">Project List</h1>
        </div>
        <div class="row" id="projects-container">
        {% for project in project_list %}
            <div class="card text-center m-3" style="width: 18rem;" id="project-{{ project.id }}">
                <div class="card-body">
                <h5 class="card-title">{{ project.name }}</h5>
                <p class="card-text">{{ project.description|slice:":100" }}{% if project.description|length > 100 %}...{% endif %}</p>
                <a href="{% url 'tasks_app:project_detail' project.id %}" class="btn btn-primary">More</a>
                </div>
            </div>
        {% endfor %}
        </div>
    <div class="row">
        <div class="ps-3 p-3">
               <a type="button" class="btn btn-success" href="{% url 'tasks_app:project_create' %}">New Project</a> 
        </div>
    </div>
    </div>

{% endblock %}
{% load static %} 
{% block scripts %}
<script src="{% static 'js/websocket_handling.js' %}"></script>
{% endblock %}

task_manager/tasks/templates/tasks/task_confirm_delete.html
{% extends "task_manager/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Are you sure you want to delete {{ task.title }}?</h1>
    </div>
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirm Delete</button>
            <a href="{% url 'tasks_app:project_detail' task.project.id %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}
{% load static %} 
{% block scripts %}
<script src="{% static 'js/websocket_handling.js' %}"></script>
{% endblock %}

task_manager/tasks/templates/tasks/task_detail.html
<!-- tasks/templates/tasks/task_detail.html -->
{% extends "task_manager/base.html" %}

{% block content %}
<h1>{{ task.title }}</h1>
<div>
    <strong>Assigned to:</strong> {{ task.assigned_to.username }}<br>
    <strong>Description:</strong> {{ task.description }}<br>
    <strong>Status:</strong> {{ task.is_completed|yesno:"Completed,In progress" }}<br>
    <strong>Created at:</strong> {{ task.created_at }}<br>
    <strong>Last Updated:</strong> {{ task.updated_at }}<br>
</div>

<a href="{% url 'tasks_app:task_edit' task.id %}">Edit Task</a> |
<a href="{% url 'tasks_app:task_delete' task.id %}">Delete Task</a>
{% endblock %}
{% load static %} 
{% block scripts %}
<script src="{% static 'js/websocket_handling.js' %}"></script>
{% endblock %}

task_manager/tasks/templates/tasks/task_form.html
{% extends "task_manager/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container p-2">
    <div class="row">
        <h2>{% if object %}Edit Task{% else %}Create Task{% endif %}</h2>
    </div>
    <form method="post" class="form">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% if field.field.widget.input_type == "checkbox" %}
                <!-- Boolean field handling (Checkbox) -->
                <div class="form-check">
                    {{ field|add_class:"form-check-input" }}
                    <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
            {% elif field.field.widget.input_type == "date" %}
                <!-- Date field handling -->
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:"form-control" }}
                </div>
            {% else %}
                <!-- Text and other field handling -->
                {{ field|add_class:"form-control" }}
            {% endif %}

            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pt-2">
           <button type="submit" class="btn btn-primary">Save</button> 
        </div>
    </form> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr(".datetimepicker", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
        });
    });
    </script>
</div>
{% endblock %}
{% load static %} 
{% block scripts %}
<script src="{% static 'js/websocket_handling.js' %}"></script>
{% endblock %}

task_manager/tasks/templates/tasks/user_profile_page.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <div class="container">
          <div class="row g-5">
            <div class="col-md-7 col-lg-8">
              <h4 class="mb-3">Profile for {{user.username}}</h4>
              <form class="needs-validation" novalidate="">
                <div class="row g-3">
                    <div class="col-12">
                        <div class="grid w-75" style="display: flex; justify-content: flex-start;">
                            <div class="g-col-6" style="flex: 1; max-width: 50%;">
                                <label for="firstName" class="form-label">First name</label>
                                <input type="text" class="form-control" id="firstName" placeholder="{{ user.first_name }}" value="" required="">
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>
                    
                            <div class="g-col-6" style="flex: 1; max-width: 50%; margin-left: 1rem;">
                                <label for="lastName" class="form-label">Last name</label>
                                <input type="text" class="form-control" id="lastName" placeholder="{{ user.last_name }}" value="" required="">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>
                        </div>
                    </div>
      
                  <div class="col-12">
                    <div class="d-flex flex-row">
                        <div class="align-self-start w-75">
                            <label for="username" class="form-label">Username</label>
                            <div class="input-group has-validation">
                            <span class="input-group-text">@</span>
                            <input type="text" class="form-control" id="username" placeholder="{{ user.username }}" required="" readonly>
                            <div class="invalid-feedback">
                                Your username is required.
                            </div>
                            </div>
                        </div>
                    </div>
                  </div>

                    <div class="col-12 pw-textbox">
                        <div class="d-flex flex-row">
                            <div class="align-self-start w-75">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="password" placeholder="••••••••••••••••" value="" readonly>
                                <div class="invalid-feedback">
                                Password Required
                                </div>
                            </div>
                        </div>
                    </div>
      
                  <div class="col-12">
                    <div class="d-flex flex-row">
                        <div class="align-self-start w-75">
                            <label for="email" class="form-label">Email <span class="text-body-secondary">(Optional)</span></label>
                            <input type="email" class="form-control" id="email" placeholder="{{ user.email }}">
                            <div class="invalid-feedback">
                            Please enter a valid email address.
                            </div>
                        </div>
                    </div>
                  </div>
      
                  <div class="col-12">
                    <div class="d-flex flex-row">
                        <div class="align-self-start w-75">
                            <label for="address2" class="form-label">Bio <span class="text-body-secondary">(Optional)</span></label>
                            <textarea class="form-control" id="userBio" rows="4" placeholder="Something about me...">{{ user.Bio }}</textarea>
                        </div>
                    </div>
                  </div>
      
                <button class="w-75 btn btn-primary ms-1" type="submit">Update</button>
              </form>
            </div>
          </div>
      </div>

{% endblock %}

{% load static %} 
{% block scripts %}
<script src="{% static 'js/user_profile.js' %}"></script>
{% endblock %}